name: Flutter CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --base-href /${{ github.event.repository.name }}/

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
